In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/rekrute_data_1.csv')

In [47]:
stop_skills = ['KS123MP6KPNJF3GFZ5TS',]

In [3]:
df

,title,country,location,date,url,skills,sectors
0,Ingénieur Etudes et Développement .NET,Maroc,Casablanca,27/09/2021,/offre-emploi-ingenieur-etudes-et-developpemen...,"['KS440W865GC4VRBW6LJP', 'KS126JR6F5V2TRCLB1H5...",Informatique
1,Data engineer Cloud,Maroc,Casablanca,27/09/2021,/offre-emploi-data-engineer-cloud-recrutement-...,"['KS122NM6B8TWBGL2X18F', 'KS125LS6N7WP4S6SFTCK...",Informatique
2,Responsable HSE (H/F),Maroc,Casablanca,27/09/2021,/offre-emploi-responsable-hse-hf-recrutement-m...,"['KS124Q3726PHM9JNS05D', 'KS1218W78FGVPVP2KXPX...",Agroalimentaire
3,Responsable Ressources Humaines (H/F),Maroc,Casablanca,27/09/2021,/offre-emploi-responsable-ressources-humaines-...,"['KS4401D6PYRMFQC4HR62', 'KS124Q3726PHM9JNS05D...",Agroalimentaire
4,Analyste Etudes Stratégiques et Montages,Maroc,Casablanca,27/09/2021,/offre-emploi-analyste-etudes-strategiques-et-...,"['ESA420F05EBBD34B3C2A', 'KS441P36DKPV9PPLT3M3...",BTP / Génie Civil
...,...,...,...,...,...,...,...
4274,Category Manager (CATMAN),Maroc,Casablanca,04/09/2021,/offre-emploi-category-manager-catman-recrutem...,"['KS1212B6QR5SK1LSD4S4', 'KS121FS74TYLW9WC52YR...",Autres services
4275,Technicien NOC,Maroc,Casablanca,03/09/2021,/offre-emploi-technicien-noc-recrutement-manpo...,"['KS123K75YYK8VGH90NCS', 'KS124S76XCNN8GYGGRBL...",Informatique
4276,Chargé de Support Applicatif,Maroc,Casablanca,03/09/2021,/offre-emploi-charge-de-support-applicatif-rec...,"['KS440WB6JXXD43XXP1GJ', 'KS123K75YYK8VGH90NCS...",Informatique
4277,Candidature Spontanée,Maroc,Mohammedia,09/02/2021,/offre-emploi-candidature-spontanee-recrutemen...,"['KS1243976G466GV63ZBY', 'KS1253H61TTR1FZWSRH4']",Centre d'appel
4278,Déposez votre Candidature Spontanée,Maroc,Tout le Maroc,12/01/2021,/offre-emploi-deposez-votre-candidature-sponta...,[],Distribution

In [35]:
# lower case to title col 
df['title'] = df['title'].str.lower()

In [45]:
df.title.value_counts()

télévendeurs/télévendeuses en émission d’appels pour un fai week-end off    13
business analyst                                                            11
technicien helpdesk francophone (h/f)                                       10
conseiller de clientèle                                                     10
conseiller en assurance francophone en réception d'appels                   10
                                                                            ..
formateur en métier de soins                                                 1
formateur en techniques de laboratoire                                       1
consultants juniors en audit et conseil en reporting esg (h/f)               1
responsable ressources humaines - chaîne hôtelière de luxe -                 1
cadre comptable                                                              1
Name: title, Length: 2845, dtype: int64

In [49]:
import collections
import ast 
# select by sector 
def get_skills(filter_key,filter_value):
    filtred_df =   df[df[filter_key].str.contains(filter_value)]
    skills_2d = filtred_df['skills'].values.tolist()
    # str to list 
    skills_2d = [ast.literal_eval(x) for x in skills_2d]
    skills_1d = [item for sublist in skills_2d for item in sublist]
    # remove noise 
    skills_1d = [skill for skill in skills_1d if skill not in stop_skills]
    return skills_1d



# test 
#get_skills('location','Casablanca')

In [50]:
# process skills (hard ,soft)
from skillNer.general_params import SKILL_DB

def process_skill_list(skill_lst):
    hard_skill_list = []
    soft_skill_list = []
    for skill in skill_lst : 
        # get skill type  
        skill_type = SKILL_DB[skill]['skill_type']
        #print(skill, skill_type)
        if skill_type == 'Hard Skill' : 
            # add to hard skill list 
            hard_skill_list.append(skill)
        elif skill_type == 'Soft Skill' : 
            # add to soft skill list 
            soft_skill_list.append(skill)
    
    # create counters 
    hard_skill_counter = collections.Counter(hard_skill_list)
    soft_skill_counter = collections.Counter(soft_skill_list)
    # get most common
    hard_skill_most_common = hard_skill_counter.most_common(10)
    soft_skill_most_common = soft_skill_counter.most_common(10)
    # map to skill name
    hard_skill_most_common = [(SKILL_DB[x[0]]['skill_name'],x[1]) for x in hard_skill_most_common]
    soft_skill_most_common = [(SKILL_DB[x[0]]['skill_name'],x[1]) for x in soft_skill_most_common]
    return hard_skill_most_common, soft_skill_most_common

In [51]:
col_name = 'title'
filter_value = 'analyst'
skills = get_skills(col_name,filter_value)
stats = process_skill_list(skills)

import pprint 
pprint.pprint(stats)

([('SQL (Programming Language)', 27),
  ('Analytics', 20),
  ('Finance', 15),
  ('Banking', 14),
  ('JIRA', 13),
  ('Computer Science', 12),
  ('Information Systems', 12),
  ('Value Added Selling (Selling Techniques)', 12),
  ('Extract Transform Load (ETL)', 12),
  ('Project Management', 11)],
 [('English Language', 44),
  ('French Language', 41),
  ('Communications', 38),
  ('Adaptability', 18),
  ('Operations', 13),
  ('Written English', 13),
  ('Integration', 11),
  ('Investigation', 11),
  ('Writing', 10),
  ('Decision Making', 10)])

In [58]:
# get skill stats 
# skill occurence in jobs 
def get_skill_uno_stats(skill_id):
    # get skill name 
    skill_name = SKILL_DB[skill_id]['skill_name']
    # get skill count 
    skill_count = df[df['skills'].str.contains(skill_id)].shape[0]
    # get occurence dates 
    occurence_dates = df[df['skills'].str.contains(skill_id)]['date'].values.tolist()

    return skill_name, skill_count,dict(collections.Counter(occurence_dates))

# test 
get_skill_uno_stats('KS123K75YYK8VGH90NCS')

('English Language',
 1366,
 {'27/09/2021': 29,
  '24/09/2021': 32,
  '23/09/2021': 18,
  '22/09/2021': 37,
  '21/09/2021': 67,
  '20/09/2021': 44,
  '19/09/2021': 7,
  '16/09/2021': 2,
  '15/09/2021': 6,
  '14/09/2021': 12,
  '13/09/2021': 32,
  '10/09/2021': 24,
  '09/09/2021': 19,
  '08/09/2021': 9,
  '07/09/2021': 18,
  '06/09/2021': 17,
  '05/09/2021': 8,
  '04/09/2021': 10,
  '03/09/2021': 11,
  '02/09/2021': 14,
  '01/09/2021': 21,
  '31/08/2021': 5,
  '30/08/2021': 9,
  '28/08/2021': 1,
  '27/08/2021': 15,
  '26/08/2021': 4,
  '25/08/2021': 5,
  '24/08/2021': 7,
  '23/08/2021': 14,
  '21/08/2021': 1,
  '19/08/2021': 4,
  '18/08/2021': 2,
  '17/08/2021': 4,
  '16/08/2021': 2,
  '14/08/2021': 1,
  '12/08/2021': 1,
  '11/08/2021': 3,
  '09/08/2021': 8,
  '07/08/2021': 2,
  '06/08/2021': 9,
  '05/08/2021': 4,
  '04/08/2021': 7,
  '03/08/2021': 6,
  '02/08/2021': 2,
  '30/07/2021': 4,
  '29/07/2021': 42,
  '28/07/2021': 24,
  '31/07/2021': 2,
  '27/07/2021': 21,
  '26/07/2021': 12,
  '25/07/2021': 3,
  '23/07/2021': 14,
  '20/07/2021': 2,
  '19/07/2021': 11,
  '17/07/2021': 2,
  '16/07/2021': 1,
  '15/07/2021': 16,
  '14/07/2021': 5,
  '13/07/2021': 21,
  '12/07/2021': 20,
  '11/07/2021': 3,
  '09/07/2021': 12,
  '08/07/2021': 13,
  '07/07/2021': 10,
  '06/07/2021': 22,
  '05/07/2021': 6,
  '03/07/2021': 1,
  '02/07/2021': 9,
  '01/07/2021': 6,
  '30/06/2021': 11,
  '29/06/2021': 11,
  '28/06/2021': 20,
  '27/06/2021': 2,
  '25/06/2021': 10,
  '24/06/2021': 19,
  '23/06/2021': 17,
  '22/06/2021': 11,
  '21/06/2021': 5,
  '20/06/2021': 3,
  '18/06/2021': 6,
  '17/06/2021': 3,
  '16/06/2021': 8,
  '15/06/2021': 13,
  '14/06/2021': 12,
  '12/06/2021': 1,
  '11/06/2021': 6,
  '10/06/2021': 6,
  '09/06/2021': 4,
  '08/06/2021': 5,
  '07/06/2021': 5,
  '04/06/2021': 3,
  '03/06/2021': 4,
  '02/06/2021': 4,
  '01/06/2021': 4,
  '03/11/2021': 17,
  '02/11/2021': 36,
  '01/11/2021': 43,
  '31/10/2021': 1,
  '30/10/2021': 3,
  '29/10/2021': 21,
  '28/10/2021': 9,
  '27/10/2021': 11,
  '26/10/2021': 11,
  '25/10/2021': 18,
  '22/10/2021': 8,
  '21/10/2021': 15,
  '20/10/2021': 5,
  '19/10/2021': 2,
  '18/10/2021': 6,
  '15/10/2021': 5,
  '14/10/2021': 16,
  '13/10/2021': 11,
  '12/10/2021': 8,
  '11/10/2021': 9,
  '08/10/2021': 9,
  '07/10/2021': 14,
  '06/10/2021': 3,
  '05/10/2021': 23,
  '04/10/2021': 11,
  '03/10/2021': 2,
  '01/10/2021': 4,
  '30/09/2021': 4,
  '29/09/2021': 6,
  '28/09/2021': 7})

In [ ]:
# get skill twins 
def get_skill_twins(skill_id):